binary_sensor:
  - platform: template
    sensors:
      motion_mary_bedroom:
        device_class: motion
        friendly_name: "Mary's Bedroom Motion Sensor"
        value_template: >-
          {{ states("sensor.linear_wapirz1_motion_sensor_alarm_level_2")|float > 0 }}
  - platform: template
    sensors:
      motion_hallway:
        device_class: motion
        friendly_name: "Hallway Motion"
        value_template: >-
          {{ states("sensor.linear_wapirz1_motion_sensor_alarm_level")|float > 0 }}
  - platform: template
    sensors:
      motion_camille_bedroom:
        device_class: motion
        friendly_name: "Camille's Bedroom Motion"
        value_template: >-
          {{ states("binary_sensor.aeotec_dsb05_multisensor_sensor") == "on" }}
  - platform: template
    sensors:
      motion_master_bedroom:
        device_class: motion
        friendly_name: "Master Bedroom Motion"
        value_template: >-
          {{ states("binary_sensor.aeotec_zw100_multisensor_6_sensor") == "on" }}

automation:
  - id: notify_motion_mary
    alias: Send notifications on motion in Mary's Room
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_mary_bedroom
        to: "on"
    condition:
      - condition: template
          value_template: >-
            {{ states("input_select.mary_status") == "Asleep" }}
    action:
      - service: notify.ios_ergisch
        data:
          title: "Motion Alert"
          message: "Mary's Bedroom"

  - id: notify_motion_hallway
    alias: Send notification on motion in hallway
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_hallway
        to: "on"
    condition:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: "armed_home"
    action:
      - service: notify.ios_ergisch
        data:
          title: "Motion Alert"
          message: "Hallway"
