## These two automations make sure the dropdown box and thermostat are always the same no matter where you change it.
- alias: Set Thermostat Mode Selector
  trigger:
    - platform: mqtt
      topic: "smartthings/Livingroom Thermostat/thermostatMode"
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.livingroom_thermostat_mode
        option: '{{ trigger.payload }}'
- alias: Set Thermostat Mode
  trigger:
  - platform: state
    entity_id: input_select.livingroom_thermostat_mode
  action:
  - service: mqtt.publish
    data_template:
      topic: "smartthings/Livingroom Thermostat/thermostatMode"
      retain: true
      payload: '{{ states.input_select.livingroom_thermostat_mode.state }}'

## These two automations make sure the heating slider and thermostat are always the same no matter where you change it.
- alias: Heating target set
  trigger:
    - platform: mqtt
      topic: "smartthings/Livingroom Thermostat/heatingSetpoint"
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.livingroom_heating_target
        value: '{{ trigger.payload}}'

 - alias: Set heating target
    trigger:
      - platform: state
        entity_id: input_number.livingroom_heating_target
    action:
      - service: mqtt.publish
        data_template:
          topic: "smartthings/Livingroom Thermostat/heatingSetpoint"
          retain: true
          payload: '{{ states.input_number.livingroom_heating_target.state | int }}'

## These two automations make sure the cooling slider and thermostat are always the same no matter where you change it.
- alias: Cooling target set
  trigger:
    - platform: mqtt
      topic: "smartthings/Livingroom Thermostat/coolingSetpoint"
  action:
    - service: input_number.set_value
      data_template:
      entity_id: input_number.livingroom_cooling_target
      value: '{{ trigger.payload}}'
 
 - alias: Set cooling target
    trigger:
      - platform: state
        entity_id: input_number.livingroom_cooling_target
    action:
      - service: mqtt.publish
        data_template:
          topic: "smartthings/Livingroom Thermostat/coolingSetpoint"
          retain: true
          payload: '{{ states.input_number.livingroom_cooling_target.state | int }}'
