- platform: zwave

- platform: generic_thermostat
  name: Living Room Thermostat Cool
  heater: input_boolean.switch_cool_living_room
  target_sensor: sensor.living_room_average_temperature
  min_temp: 60
  max_temp: 90
  # target_temp: 72
  ac_mode: True
  initial_operation_mode: "auto"
  unit_of_measurement: "째F"

- platform: generic_thermostat
  name: Living Room Thermostat Heat
  heater: input_boolean.switch_heat_living_room
  target_sensor: sensor.living_room_average_temperature
  min_temp: 60
  max_temp: 90
  # target_temp: 65
  ac_mode: False
  initial_operation_mode: "auto"
  unit_of_measurement: "째F"
  
- platform: generic_thermostat
  name: Bedroom Thermostat Cool
  heater: input_boolean.switch_cool_bedroom
  target_sensor: sensor.bedroom_average_temperature
  min_temp: 60
  max_temp: 90
  # target_temp: 72
  ac_mode: True
  initial_operation_mode: "auto"
  unit_of_measurement: "째F"
  
- platform: generic_thermostat
  name: Bedroom Thermostat Heat
  heater: input_boolean.switch_heat_bedroom
  target_sensor: sensor.bedroom_average_temperature
  min_temp: 60
  max_temp: 90
  # target_temp: 65
  ac_mode: False
  initial_operation_mode: "auto"
  unit_of_measurement: "째F"
