- platform: zwave

- platform: generic_thermostat
  name: Living Room Thermostat
  heater: input_boolean.heater_switch
  target_sensor: sensor.living_room_average_temperature
  min_temp: 60
  max_temp: 80
  target_temp: 72
  ac_mode: True
  initial_operation_mode: "off"
  unit_of_measurement: "°F"
  

