# Weather prediction
- platform: yr

# Smartthings MQTT
- platform: mqtt
  name: "Bedroom Sensor Motion"
  state_topic: "smartthings/Bedroom Sensor/motion"
- platform: mqtt
  name: "Bedroom Sensor Temperature"
  state_topic: "smartthings/Bedroom Sensor/temperature"
  unit_of_measurement: "°"
- platform: mqtt
  name: "Bedroom Sensor Humidity"
  state_topic: "smartthings/Bedroom Sensor/humidity"
  unit_of_measurement: "%"
- platform: mqtt
  name: "Bedroom Sensor Illuminance"
  state_topic: "smartthings/Bedroom Sensor/illuminance"
  unit_of_measurement: "lux"
- platform: mqtt
  name: "Bedroom Sensor Battery"
  state_topic: "smartthings/Bedroom Sensor/battery"
- platform: mqtt
  name: "Living Room Sensor Motion"
  state_topic: "smartthings/Living Room Sensor/motion"
- platform: mqtt
  name: "Living Room Sensor Temperature"
  state_topic: "smartthings/Living Room Sensor/temperature"
  unit_of_measurement: "°"
- platform: mqtt
  name: "Living Room Sensor Humidity"
  state_topic: "smartthings/Living Room Sensor/humidity"
  unit_of_measurement: "%"
- platform: mqtt
  name: "Living Room Sensor Illuminance"
  state_topic: "smartthings/Living Room Sensor/illuminance"
  unit_of_measurement: "lux"
- platform: mqtt
  name: "Living Room Sensor Battery"
  state_topic: "smartthings/Living Room Sensor/battery"
  unit_of_measurement: "%"
- platform: mqtt
  name: "Water Leak Sensor Temperature"
  state_topic: "smartthings/Water Leak Sensor/temperature"
  unit_of_measurement: "°"
- platform: mqtt
  name: "Water Leak Sensor Water"
  state_topic: "smartthings/Water Leak Sensor/water"
- platform: mqtt
  name: "Water Leak Sensor Battery"
  state_topic: "smartthings/Water Leak Sensor/battery"
  unit_of_measurement: "%"

## Virtual sensors
- platform: template
  sensors:
    bedroom_average_temperature:
      friendly_name: Bedroom Average Temperature
      value_template: >-
        {{((float(states.sensor.bedroom_sensor_temperature.state) +
        float(states.sensor.gocontrol_thermostat_bedroom_temperature.state)) / 2)|round(2)}}
      unit_of_measurement: "°"

- platform: template
  sensors:
    living_room_average_temperature:
      friendly_name: Living Room Average Temperature
      value_template: >-
        {{((float(states.sensor.living_room_sensor_temperature.state) +
        float(states.sensor.water_leak_sensor_temperature.state) +
        (float(states.sensor.gocontrol_thermostat_living_room_temperature.state)) * 2) / 4) | round(2)}}
      unit_of_measurement: "°"

## System Monitor
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: "/"
    - type: disk_free
      arg: "/"
    - type: memory_use_percent
    - type: memory_free
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: since_last_boot

## Arlo
- platform: arlo
  monitored_conditions:
    - captured_today
    - last_capture
    - total_cameras
    # - battery_level
    # - signal_strength
