# Weather prediction
- platform: yr

# Smartthings MQTT
- platform: mqtt
  name: "Water Leak Sensor Temperature"
  state_topic: "smartthings/Water Leak Sensor/temperature"
  unit_of_measurement: "째F"
- platform: mqtt
  name: "Water Leak Sensor Water"
  state_topic: "smartthings/Water Leak Sensor/water"
- platform: mqtt
  name: "Water Leak Sensor Battery"
  state_topic: "smartthings/Water Leak Sensor/battery"
  unit_of_measurement: "%"

## Virtual sensors
- platform: template
  sensors:
    bedroom_average_temperature:
      friendly_name: Bedroom Average Temperature
      value_template: >-
        {{(((float(states.sensor.aeotec_multisensor_temperature_bedroom.state) * 4) +
        float(states.sensor.gocontrol_thermostat_bedroom_temperature.state)) / 5)| round(1)}}
      unit_of_measurement: "째F"

- platform: template
  sensors:
    living_room_average_temperature:
      friendly_name: Living Room Average Temperature
      value_template: >-
        {{(((float(states.sensor.aeotec_multisensor_temperature_living_room.state) * 2) +
        float(states.sensor.water_leak_sensor_temperature.state) +
        (float(states.sensor.gocontrol_thermostat_living_room_temperature.state)) * 5) / 8) | round(1)}}
      unit_of_measurement: "째F"

- platform: template
  sensors:
    all_rooms_temperature:
      friendly_name: Average Temperature
      value_template: >-
        {{(((float(states.sensor.aeotec_multisensor_temperature_living_room.state) * 2) +
        float(states.sensor.gocontrol_thermostat_living_room_temperature.state) +
        float(states.sensor.gocontrol_thermostat_bedroom_temperature.state) +
        float(states.sensor.water_leak_sensor_temperature.state) +
        (float(states.sensor.aeotec_multisensor_temperature_bedroom.state) * 2)) / 7) | round(1)}}
      unit_of_measurement: "째F"

- platform: template
  sensors:
    all_rooms_humidity:
      friendly_name: Average Humidity
      value_template: >-
        {{(float(states.sensor.aeotec_multisensor_relative_humidity_living_room.state) +
        float(states.sensor.aeotec_multisensor_relative_humidity_bedroom.state)) / 2
        | round(1)}}
      unit_of_measurement: "%"

## System Monitor
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: "/"
    - type: disk_free
      arg: "/"
    - type: memory_use_percent
    - type: memory_free
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: since_last_boot

# ## Arlo
# - platform: arlo
#   monitored_conditions:
#     - captured_today
#     - last_capture
#     - total_cameras
#     - battery_level
#     - signal_strength

## ZWave Batteries
- platform: template
  sensors:
    aeotec_multisensor_living_room_battery:
      friendly_name: "Living Room Multisensor Battery"
      unit_of_measurement: "%"
      value_template: >-
        {{ state_attr("zwave.aeotec_multisensor_living_room", "battery_level") }}
    aeotec_multisensor_bedroom_battery:
      friendly_name: "Bedroom Multisensor Battery"
      unit_of_measurement: "%"
      value_template: >-
        {{ state_attr("zwave.aeotec_multisensor_bedroom", "battery_level") }}

- platform: time_date
  display_options:
    - "time"
    - "date"
    - "beat"

- platform: template
  sensors:
    weekday:
      friendly_name: Weekday
      value_template: >-
        {{ now().strftime("%A") }}
      icon_template: 
        mdi:calendar
