# Weather prediction
- platform: yr

# Smartthings MQTT
- platform: mqtt
  name: "Water Leak Sensor Temperature"
  state_topic: "smartthings/Water Leak Sensor/temperature"
  unit_of_measurement: "°F"
- platform: mqtt
  name: "Water Leak Sensor Water"
  state_topic: "smartthings/Water Leak Sensor/water"
- platform: mqtt
  name: "Water Leak Sensor Battery"
  state_topic: "smartthings/Water Leak Sensor/battery"
  unit_of_measurement: "%"

## System Monitor
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: "/"
    - type: disk_free
      arg: "/"
    - type: memory_use_percent
    - type: memory_free
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: last_boot

# ## Arlo
# - platform: arlo
#   monitored_conditions:
#     - captured_today
#     - last_capture
#     - total_cameras
#     - battery_level
#     - signal_strength

## ZWave Batteries
- platform: template
  sensors:
    aeotec_multisensor_living_room_battery:
      friendly_name: "Living Room Multisensor Battery"
      unit_of_measurement: "%"
      value_template: >-
        {{ state_attr("zwave.aeotec_multisensor_living_room", "battery_level") }}
    aeotec_multisensor_bedroom_battery:
      friendly_name: "Bedroom Multisensor Battery"
      unit_of_measurement: "%"
      value_template: >-
        {{ state_attr("zwave.aeotec_multisensor_bedroom", "battery_level") }}

- platform: time_date
  display_options:
    - "time"
    - "date"
    - "beat"

- platform: template
  sensors:
    weekday:
      friendly_name: Weekday
      value_template: >-
        {% set currentTime = strptime(states.sensor.date.state, "%Y-%m-%d") %}
        {{ currentTime.strftime("%A") }}
      icon_template:
        mdi:calendar
