title: The Grand Ohio - Home Assistant
# Include external resources
resources:
  - url: /local/my-custom-card.js
    type: js
  - url: /local/my-webfont.css
    type: css

# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
background: center / cover no-repeat url("/background.png") fixed
# Exclude entities from "Unused entities" view
# excluded_entities:
#   - weblink.router
views:
    # View tab title.
  - title: Home
    # Optional unique id for direct access /lovelace/${id}
    id: home
    # Optional background (overwrites the global background).
    # background: radial-gradient(crimson, skyblue)
    # Each view can have a different theme applied. Theme should be defined in the frontend.
    theme: dark-mode
    # The cards to show on this view.
    cards:
        # The filter card will filter entities for their state
      # - type: entity-filter
      #   entities:
      #     - device_tracker.ergisch
      #     - device_tracker.angela_pfammatters_iphone
      #   state_filter:
      #     - 'home'
      #   card:
      #     type: glance
      #     title: People that are home
      - type: entities
        title: Home Status
        entities:
          - input_select.home_mode
          - input_select.presence
          - input_select.hvac_mode
      - type: vertical-stack
        cards:
          - type: sensor
            entity: sensor.all_rooms_temperature
            name: Average Home Temparature
          - type: sensor
            entity: sensor.all_rooms_humidity
            name: Average Home Humidity
      - type: entities
        title: Routines
        entities:
          - script.makecoffee
          - script.goodmorning
          - script.goodbye
          - script.imback
          - script.bedtime
          - script.getmellowed
          - script.goodnight
      - type: media-control
        entity: media_player.denon
      - type: vertical-stack
        cards:
          - type: conditional
            conditions:
              - entity: media_player.denon
                state: "playing"
            card:
              type: media-control
              entity: media_player.denon
          - type: conditional
            condition:
              - entity: media_player.living_room_speaker
                state: "playing"
            card:
              type: media-control
              entity: media_player.living_room_speaker
      - type: weather-forecast
        entity: weather.dark_sky


        # The picture entity card will represent an entity with a picture
      # - type: picture-entity
      #   image: https://www.home-assistant.io/images/default-social.png
      #   entity: light.bed_light

  - title: Living Room
    id: living_room
    theme: dark-mode
    cards:
      - type: glance
        name: Living Room Status
        entities:
          - sensor.aeotec_multisensor_burglar_living_room
          - sensor.living_room_average_temperature
          - sensor.aeotec_multisensor_temperature_living_room
          - sensor.gocontrol_thermostat_living_room_temperature
          - sensor.water_leak_sensor_temperature
          - sensor.aeotec_multisensor_relative_humidity_living_room
      - type: conditional
        conditions:
          - entity: input_select.hvac_mode
            state: "cooling"
        card:
          type: entities
          entities:
            - climate.living_room_thermostat_cool
      - type: conditional
        conditions:
          - entity: input_select.hvac_mode
            state: "heating"
        card:
          type: entities
          entities:
            - climate.living_room_thermostat_heat
      - type: media-control
        entity: media_player.denon
      - type: media-control
        entity: media_player.living_room_speaker
      - type: glance
        entities:
          - entity: light.aeotec_bathroom_light
            name: Bathroom
          - entity: light.aeotec_entry_light
            name: Entry
          - entity: light.aeotec_kitchen_counter_light
            name: Counter
          - entity: light.closet_light
            name: Closet
          - entity: light.grandmas_lamp
            name: Grandma's
          - entity: light.hallway_light
            name: Hall
          - entity: light.metal_lamp
            name: Metal
          - entity: light.pop_socket_light
            name: Pop Socket

  - title: Bedroom
    id: bedroom
    theme: dark-mode
    cards:
      - type: glance
        title: Bedroom Status
        entities:
          - binary_sensor.aeotec_multisensor_sensor_bedroom
          - sensor.bedroom_average_temperature
          - sensor.aeotec_multisensor_temperature_bedroom
          - sensor.aeotec_multisensor_relative_humidity_bedroom
          - sensor.aeotec_multisensor_luminance_bedroom
      - type: conditional
        conditions:
          - entity: input_select.hvac_mode
            state: "cooling"
        card:
          type: entities
          entities:
            - climate.bedroom_thermostat_cool
      - type: conditional
        conditions:
          - entity: input_select.hvac_mode
            state: "heating"
        card:
          type: entities
          entities:
            - climate.bedroom_thermostat_heat
      - type: media-control
        entity: media_player.bedroom_speaker
      - type: glance
        title: Bedroom Lights
        entities:
          - entity: light.bedroom_canopy
            name: Canopy
          - entity: light.bedroom_lamp
            name: Bedside
          - entity: light.camilles_desk_lamp
            name: Desk
          - entity: light.bedroom_closet
            name: Closet


  - icon: mdi:thermometer-lines
    title: Climate
    cards:
      - type: glance
        name: Living Room Status
        entities:
          - sensor.living_room_average_temperature
          - sensor.aeotec_multisensor_temperature_living_room
          - sensor.gocontrol_thermostat_living_room_temperature
          - sensor.water_leak_sensor_temperature
          - sensor.aeotec_multisensor_relative_humidity_living_room
      - type: entities
        title: Living Room Heating
        entities:
          - climate.gocontrol_thermostat_living_room_heating_setpoint
          - climate.living_room_thermostat_heat
          - climate.linear_gctbz48_battery_powered_zwave_thermostat_unused_0
          - climate.linear_gctbz48_battery_powered_zwave_thermostat_dry_air
          - climate.linear_gctbz48_battery_powered_zwave_thermostat_heating_econ
      # - type: thermostat
      #   entity: climate.gocontrol_thermostat_living_room_heating_setpoint
      - type: glance
        name: Bedroom Status
        entities:
          - sensor.bedroom_average_temperature
          - sensor.gocontrol_thermostat_bedroom_temperature
          - sensor.aeotec_multisensor_temperature_bedroom
      - type: entities
        title: Bedroom Heating
        entities:
          - climate.bedroom_thermostat_heat
          - climate.gocontrol_thermostat_bedroom_heating
      - type: thermostat
        entity: climate.bedroom_thermostat_heat

    # Specify a tab icon if you want the view tab to be an icon.
  - icon: mdi:settings
    # Title of the view. Will be used as the tooltip for tab icon
    title: Settings
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            name: Inputs
            entities:
              - input_boolean.testing
              - input_select.home_mode
              - input_select.presence
              - input_select.hvac_mode
          - type: entities
            name: Cleaner Window Setup
            entities:
              - input_select.clean_day
              - input_datetime.clean_start
              - input_datetime.clean_end
      - type: sensor
        entity: sensor.load_1m
      - type: vertical-stack
        cards:
          - type: gauge
            title: Disk Usage
            entity: sensor.disk_use_percent_
          - type: entities
            entities:
              - sensor.disk_free_
          - type: gauge
            title: Memory
            entity: sensor.memory_use_percent
          - type: entities
            entities:
              - sensor.memory_free
          - type: entities
            entities:
              - sensor.since_last_boot


        # The markdown card will render markdown text.
      # - type: markdown
      #   title: Lovelace
      #   content: >
      #     Welcome to your **Lovelace UI**.
