title: The Grand Ohio - Home Assistant
# Include external resources
resources:
  - url: /local/my-custom-card.js
    type: js
  - url: /local/my-webfont.css
    type: css

# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
background: center / cover no-repeat url("/background.png") fixed
# Exclude entities from "Unused entities" view
# excluded_entities:
#   - weblink.router
views:
    # View tab title.
  - title: Home
    # Optional unique id for direct access /lovelace/${id}
    id: home
    # Optional background (overwrites the global background).
    # background: radial-gradient(crimson, skyblue)
    # Each view can have a different theme applied. Theme should be defined in the frontend.
    theme: dark-mode
    # The cards to show on this view.
    cards:
        # The filter card will filter entities for their state
      # - type: entity-filter
      #   entities:
      #     - device_tracker.ergisch
      #     - device_tracker.angela_pfammatters_iphone
      #   state_filter:
      #     - 'home'
      #   card:
      #     type: glance
      #     title: People that are home
      - type: entities
        title: Home Status
        entities:
          - input_select.home_mode
          - input_select.presence
          - input_select.hvac_mode
      - type: sensor
        entity: sensor.all_rooms_temperature
        name: Average Home Temparature
      - type: sensor
        entity: sensor.all_rooms_humidity
        name: Average Home Humidity
      - type: entities
        title: Routines
        entities:
          - script.makecoffee
          - script.goodmorning
          - script.goodbye
          - script.imback
          - script.bedtime
          - script.getmellowed
          - script.goodnight
      - type: media-control
        entity: media_player.denon
      - type: weather-forecast
        entity: weather.dark_sky


        # The picture entity card will represent an entity with a picture
      # - type: picture-entity
      #   image: https://www.home-assistant.io/images/default-social.png
      #   entity: light.bed_light

  - title: Living Room
    id: living_room
    theme: dark-mode
    cards:
      - type: glance
        title: Living Room Status
        entities:
          - binary_sensor.aeotec_multisensor_sensor_bedroom
          - sensor.bedroom_average_temperature
          - sensor.aeotec_multisensor_temperature_bedroom
          - sensor.aeotec_multisensor_relative_humidity_bedroom
          - sensor.aeotec_multisensor_luminance_bedroom
      - type: conditional
        conditions:
          - entity: input_select.hvac_mode
            state: "cooling"
        card:
          type: thermostat
          entity: climate.climate.bedroom_thermostat_cool
      - type: conditional
        conditions:
          - entity: input_select.hvac_mode
            state: "heating"
        card:
          type: thermostat
          entity: climate.climate.bedroom_thermostat_heat
      - type: media-control
        entity: media_player.denon
      - type: media-control
        entity: media_player.living_room_speaker
      - type: glance
        entities:
          - group.livingroomlights

  - title: Bedroom
    id: bedroom
    theme: dark-mode
    cards:
      - type: glance
        title: Bedroom Status
        entities:
          - binary_sensor.aeotec_multisensor_sensor_bedroom
          - sensor.bedroom_average_temperature
          - sensor.aeotec_multisensor_temperature_bedroom
          - sensor.aeotec_multisensor_relative_humidity_bedroom
          - sensor.aeotec_multisensor_luminance_bedroom
      - type: thermostat
        entity: climate.climate.bedroom_thermostat_heat
      - type: media-control
        entity: media_player.bedroom_speaker
      - type: glance
        title: Bedroom Lights
        entities:
          - group.bedroomlights

      # - type: conditional
      #   conditions:
      #     - entity: input_select.hvac_mode
      #       state: "cooling"
      #   card:
      #     type: thermostat
      #     entity: climate.climate.bedroom_thermostat_cool
      # - type: conditional
      #   conditions:
      #     - entity: input_select.hvac_mode
      #       state: "heating"
      #   card:
      #     type: thermostat
      #     entity: climate.climate.bedroom_thermostat_heat

    # Specify a tab icon if you want the view tab to be an icon.
  - icon: mdi:settings
    # Title of the view. Will be used as the tooltip for tab icon
    title: Settings
    cards:
        # Entities card will take a list of entities and show their state.
      - type: entities
        # Title of the entities card
        title: Example
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        entities:
          - light.kitchen
          - switch.ac
          - entity: light.living_room
            # Override the name to use
            name: LR Lights

        # The markdown card will render markdown text.
      # - type: markdown
      #   title: Lovelace
      #   content: >
      #     Welcome to your **Lovelace UI**.
