input_datetime:
  alarm_time_camille:
    name: Camille's Alarm Time
    has_date: false
    has_time: true

automation:
  - id: wakeup_camille
    alias: Wakeup Camille
    trigger:
      - platform: template
        value_template: >-
          {{ states.sensor.time.state == states.input_datetime.alarm_time_camille.state[0:5] }}
    condition:
      - condition: template
        value_template: >-
          {{ states("input_select.camille_status") != "Away" }}
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
      - service: script.turn_on
        entity_id: script.goodmorning_camille
      - service: media_player.play_media
        data:
          entity_id: media_player.camilles_speaker
          media_content_id: "https://dl.dropboxusercontent.com/s/mpdyuzl5svyuxmq/Rooster%20Crowing-SoundBible.com-43612401.mp3"
          media_content_type: "music"

automation:
  - id: status_awake_camille
    alias: Status: Camille Awake
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_camille_bedroom
        to: "on"
    condition:
      - condition: template
        value_template: >-
          {{ states("input_select.camille_status") == "Asleep" }}
      - condition: template
        value_tempate: >-
          {{ states("sensor.time") >= states("input_datetime.alarm_time_camille")[0:5] and
             states("sensor.time") <= "14:00" }}
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.camille_status
          option: "Home"

  - id: lights_bedroom_camille_on
    alias: Lights: Camille's Bedroom
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_camille_bedroom
        to: "on"
    condition:
      - condition: template
        value_template: >-
          {{ states("input_select.camille_status") != "Asleep" }}
    action:
      - service: light.turn_on
        data:
          entity_id:
            - group.light_camille_bedroom

script:
  goodmorning_camille:
    alias: Goodmorning Camille
    sequence:
      - service: light.turn_on
        data:
          entity_id:
            - group.light_camille_bedroom
      - service: media_player.volume_set
        data:
          entity_id: media_player.camilles_speaker
          volume_level: 0.9

  goodnight_camille:
    alias: Good Night Camille
    sequence:
      - service: light.turn_off
        data:
          entity_id:
            - light.grandmas_lamp
            - light.bedroom_canopy
      - service: input_select.select_option
        data:
          entity_id: input_select.home_mode
          option: "Quiet"
      - service: input_select.select_option
        data:
          entity_id: input_select.camille_status
          option: "Asleep"
      - service: media_player.volume_set
        data:
          entity_id: media_player.camilles_speaker
          volume_level: 0.2
      - service: notify.notify
        data:
          title: "Camille"
          message: "Bedtime"
