script:
  make_the_coffee:
    alias: Make the Coffee
    sequence:
      - service: light.turn_on
        data:
          brightness: 255
          entity_id:
            - light.christmas_tree_lights
            - light.living_room_light
            - light.accordian_lamp
      - service: input_select.select_option
        data:
          entity_id: input_select.home_mode
          option: "Quiet"
      - service: media_player.volume_set
        data:
          entity_id: media_player.living_room_display
          volume_level: 0.8
      - service: media_player.volume_set
        data:
          entity_id: media_player.living_room_tv
          volume_level: 0.3

automation:
  - id: make_the_coffee
    alias: Run make the coffee
    trigger:
      - platform: time
        at: "6:40:00"
    condition:
      - condition: state
        entity_id: input_select.presence
        state: "Home"
      - condition: state
        entity_id: input_select.home_mode
        state: "Sleep"
  action:
    - service: script.makecoffee
