sensor:
  - platform: template
    sensors:
      whole_house_temperature:
        friendly_name: Whole House Temperature
        value_template: >-
          {{ ((states("sensor.aeotec_dsb05_multisensor_temperature")|float +
              states("sensor.aeotec_zw100_multisensor_6_temperature")|float +
              states("sensor.linear_wapirz1_motion_sensor_temperature")|float +
              states("sensor.linear_wapirz1_motion_sensor_temperature_2")|float) / 4)|round(1) }}
        unit_of_measurement: "°F"
